language: cpp

compiler:
  - gcc
  - clang


before_script:
  - autoreconf -fi

script:
  - ./configure && make && make check

  - # Now try building with CMake.
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_INSTALL_DIR=~/ColPack
  - make
  - ctest
  - make install
