language: cpp

compiler:
  - gcc


before_script:
  - autoreconf -fi

script:
  - ./configure && make && make check

  - # Now try building with CMake.
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_INSTALL_PREFIX=~/ColPack
  - make
  - ctest
- make install
