language: cpp


#matrix:
#  include:
#    # works on Precise and Trusty
#    - env:
#        - MATRIX_EVAL="CC=clang && CXX=clang++ && CXX_FLAG-fopenmp=libomp"#

 # works on Precise and Trusty
#    - env:
#        - MATRIX_EVAL="CC=gcc && CXX=g++ && CXX_FLAG-fopenmp=libomp"
        
compiler: g++
before_script:
  - autoreconf -fi

script:
  - ./configure && make && make check

  - # Now try building with CMake.
  - mkdir cmake
  - cd cmake
  - fullpath=$(pwd)
  - cmake .. -DCMAKE_INSTALL_PREFIX:PATH=$(fullpath)
  - make
  - ctest
  - make install
