language: cpp
matrix:
  include:
  -compiler: gcc
  before_script:  autoreconf -fi
  script: ./configure --prefix=~/ColPack && make && make check

    - # Now try building with CMake.
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_INSTALL_PREFIX=~/ColPack
    - make
    - ctest
    - make install
  
  -compiler: clang
  before_script: autoreconf -fi
  script: ./configure --prefix=~/ColPack --disable-openmp && make && make check

    - # Now try building with CMake.
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_INSTALL_PREFIX=~/ColPack
    - make
    - ctest
    - make install

