language: cpp

before_install:
  - sudo apt-get install -y libxml2-dev
  
#matrix:
#  include:
#    # works on Precise and Trusty
#    - env:
#        - MATRIX_EVAL="CC=clang && CXX=clang++ && CXX_FLAG-fopenmp=libomp"#

 # works on Precise and Trusty
#    - env:
#        - MATRIX_EVAL="CC=gcc && CXX=g++ && CXX_FLAG-fopenmp=libomp"
        
#compiler: g++-4.9


addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake-data
      - cmake

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8

#before_script:
#  - autoreconf -fi

script:
#  - ./configure && make && make check

  - # Now try building with CMake.
  - mkdir cmake
  - cd cmake
  - fullpath=$(pwd)
  - cmake .. -DCMAKE_INSTALL_PREFIX:PATH=$(fullpath)
  - make
  - ctest
  - make install


